name: thesis-env
channels:
  - defaults
dependencies:
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=38.0.1
  - flask=2.2.2
  - gunicorn=20.1.0
  - idna=3.4
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - libffi=3.4.2
  - markupsafe=2.1.1
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.8
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.5.0
  - sqlite=3.40.0
  - tk=8.6.12
  - tzdata=2022g
  - urllib3=1.26.13
  - werkzeug=2.2.2
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - pip:
      - aniso8601==9.0.1
      - flask-restful==0.3.9
      - marshmallow==3.19.0
      - packaging==22.0
      - pytz==2022.7
      - six==1.16.0
